services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: salo_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: salo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salo_db
    ports:
      - "3306:3306"
    volumes:
      - salo_db:/var/lib/mysql

volumes:
  salo_db: 
